version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketappdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres_db:5432/marketappdb"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
