import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";
import NavBar from "@/components/navigation/NavBar";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar currentUser={currentUser} />
        {children}
        <Script
          type="text/javascript"
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=5b76dbf44c074d8fe2cfa952e9f1fcda&libraries=services,clusterer&autoload=false"
        />
      </body>
    </html>
  );
}
